# Generated by Django 3.0.4 on 2020-03-21 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0002_board_card_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.checklist'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.board'),
        ),
    ]
