# Generated by Django 3.0.4 on 2020-03-21 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_board_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='description',
            new_name='detail',
        ),
    ]
